steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'southamerica-east1-docker.pkg.dev/fiap-tech-challenge-1/tech-challenge/tech-challenge:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/fiap-tech-challenge-1/tech-challenge/tech-challenge:latest']