apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tech-challenge-service
spec:
  template:
    spec:
      containers:
        - image: southamerica-east1-docker.pkg.dev/fiap-tech-challenge-1/tech-challenge/tech-challenge:latest
          env:
          ports:
            - containerPort: 4000